# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'  # Java 17 para compatibilidad
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean verify'  # Cambiado de 'package' a 'verify' para ejecutar tests
    options: '-Dserenity.take.screenshots=FOR_EACH_ACTION -Dwebdriver.driver=remote'

- task: Maven@3
  displayName: 'Generate Serenity Aggregate Reports'
  inputs:
    mavenPomFile: 'pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    goals: 'serenity:aggregate'
    options: '-Dserenity.compress.filenames=true'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Serenity Reports'
  inputs:
    pathToPublish: 'target/site/serenity'
    artifactName: 'SerenityTestReports'